# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'The Pendulum' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for The Pendulum
    pod 'Singular-SDK'
    pod 'PapaParse', '~> 5.0'
end
